# Configuration properties for Theta Terminal 3

host = "localhost"
port = 25503
log_directory = "/tmp"
username = "ricardo@figment.com.mx"
password = "Z;Ux>+~PRcTQ@]ad4)#V"

[mdds_server]
host = "mdds-01.thetadata.us"
port = 443
tls = true
